### ISSUE TITLE
Cannot find namespace 'scrollReveal'

### ISSUE THREAD

**Issue by LiveLikeCounter** [tinesoft/ng-scrollreveal#66] opened 2017-10-25 15:21 UTC
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
> macOS(Yosemite)

### Versions.
Output from: `ng --version`:
```
@angular/cli: 1.4.5
node: 7.10.0
os: darwin x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.4.5
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
typescript: 2.3.4
```

### Repro steps.
I followed the installation steps as described:

1. install 'scrollreveal',  'ng-scrollreveal' and '@types/scrollreveal' 
2. added to my app.module.ts like "import { NgsRevealModule } from 'ng-scrollreveal';"
3. used in app.component.ts as:
```
import { Component } from '@angular/core';
import { NgsRevealConfig } from 'ng-scrollreveal';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  providers: [NgsRevealConfig]
})
export class AppComponent {

  constructor(config: NgsRevealConfig) {
    // customize default values of ng-scrollreveal directives used by this component tree
    config.duration = 5000;
    config.easing = 'cubic-bezier(0.645, 0.045, 0.355, 1)';
    config.delay = 2000;
    config.scale = 0.9;
  }

}
```

My package.json: 

```
{
  "name": "project",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "bootstrap": "^4.0.0-beta.2",
    "core-js": "^2.4.1",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "jquery.easing": "^1.4.1",
    "ng-scrollreveal": "^2.1.0",
    "popper.js": "^1.12.6",
    "rxjs": "^5.4.2",
    "scrollreveal": "^3.3.6",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.5",
    "@angular/compiler-cli": "^4.2.4",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "@types/scrollreveal": "0.0.3",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.3.3"
  }
}
```

### The log given by the failure.
```
ERROR in /Users/app/Documents/AngularProjects/project/node_modules/ng-scrollreveal/services/ngs-reveal.service.d.ts (9,19): Cannot find namespace 'scrollReveal'.
ERROR in /Users/app/Documents/AngularProjects/project/node_modules/ng-scrollreveal/services/ngs-reveal.service.d.ts (27,63): Cannot find namespace 'scrollReveal'.
ERROR in /Users/app/Documents/AngularProjects/project/node_modules/ng-scrollreveal/services/ngs-reveal.service.d.ts (35,109): Cannot find namespace 'scrollReveal'.
ERROR in /Users/app/Documents/AngularProjects/project/node_modules/ng-scrollreveal/services/ngs-reveal.service.d.ts (1,1): Cannot find type definition file for 'scrollreveal'.
```

### Desired functionality.
No build error :)

**Comment by tinesoft** [comment] 2017-10-25 16:24
Hi!

Did you add scrollreveal in "scripts" section of you're consuming app's `.angular-cli.json` file?

 ```
 "scripts": [
        "../node_modules/scrollreveal/dist/scrollreveal.js"
      ],
 ```

**Comment by LiveLikeCounter** [comment] 2017-10-25 21:02
Yes! Sorry I didn't described before

**Comment by rezonjov** [comment] 2017-11-21 09:03
I did exactly like the readme but it also says `Cannot find namespace 'scrollReveal'`
Angular 4.4.6, CLI 1.5.0-rc.2

**Comment by tinesoft** [comment] 2017-11-21 17:34
Hi guys,

I could not reproduce your errors (just tried from a fresh project created with Angular CLI 1.5.0).

I would suggest a ` rm -rf node_modules` followed by `npm install`or `yarn install` to make sure that all `dependencies` and `devDependencies` are up-to-date.

If still not working, please create a repro project on github and let me know.


Cheers!

**Comment by juanpmarengo** [comment] 2017-11-21 17:58
Same issue.
ScrollReveal version 3.3.6.
Angular version 4.3.2.
Ng2ScrollReveal version 1.0.1.

> {
   ...
    "apps": [{
        ...
        "scripts": [
            "node_modules/scrollreveal/dist/scrollreveal.js"
        ]
    }],
  ...
}

angular-cli.json

> ERROR ReferenceError: ScrollReveal is not defined
    at new NgsRevealService (ngs-reveal.service.js?bfa2:12)

I'm using yarn.

**Comment by tinesoft** [comment] 2017-11-21 18:02
Hi,

The path in `.angular-cli.json` should be:

```
    "scripts": [
        "../node_modules/scrollreveal/dist/scrollreveal.js"
      ],
```
 _(notice the leading **"../"** in the path)_

**Comment by juanpmarengo** [comment] 2017-11-21 18:35
That depends on where is you .json and node_modules, anyway i tried your suggestion and didn't work.

**Comment by tinesoft** [comment] 2017-11-21 18:45
You're right ( i had assumed your project had the default structure as generated by ng cli).

I don't know how your app structure is, but the error you're having, clearly indicates that the scrollreveal.js could not be found...

Also, please note that the current version of the library is `ng-scrollreveal@2.1.0` and not `ng2-scrollReveal@1.0.1`.

**Comment by juanpmarengo** [comment] 2017-11-22 15:57
I forget to say that didn't work.

**Comment by juanpmarengo** [comment] 2017-11-22 18:06
I found a solution for my JHipster project which uses yarn and webpack (angular-cli.json is ignored). You have to import ScrollRevealJs in webpack.common.js, vendor.js and index.html. I can go deeper if someone need it.

**Comment by tinesoft** [comment] 2017-11-22 19:12
Thanks @juanpmarengo  for your investigations! 👍 

I was in the process of installing `generator-jhipster` on my machine to try reproduce the issue myself...

Anyway, i am closing this ticket for now.  For future readers, if you are encountering the same problem again, make sure that scrollrevealJS is taken into consideration by your build system (if different from documented basic Angular CLI or SystemJS)

**Closed by tinesoft** 2017-11-22 19:12 UTC

**Comment by thienedits** [comment] 2017-12-07 07:30
You probably forgot to add the scrollreveal types. This worked for me after adding the types.

`npm install --save-dev @types/scrollreveal`
